language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a

android:
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

before_install:
  - chmod +x gradlew

before_script:
  # Create and start emulator
#  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
#  - emulator -avd test -no-skin -no-audio -no-window &
#  - adb wait-for-device
#  - adb shell input keyevent 82 &

#script: ./gradlew build connectedCheck
script: ./gradlew build